server:
  port: 8082



rest:
  client:
    core:
      users:
        host: http://localhost:8080
      thirdUsers:
        host: http://localhost:8080
      vehicle:
        host: http://localhost:8080
      thirdVehicle:
        host: http://localhost:8080
      policies:
        host: http://localhost:8081
